### ISSUE TITLE
📽️ YouTube video picker

### ISSUE THREAD

**Issue by petrvozak** [Kentico/custom-element-samples#2]
Content editor can search and pick a video from YouTube. It allows him to link related YouTube video with the given content entry without actually leaving Kentico Cloud admin UI. Developer can then render selected video as a part of the output presentation to provide complete information to the content consumer.

### Accept criteria
- There is a preview of the selected video. It helps content editor to be more confident that the chosen video is the right one.

### Proposed solution
A custom element allowing to search and select video from YouTube

**Comment by ileshmistry** [comment]
Looks like an interesting one 😉. I could have a look at this.

**Comment by petrsvihlik** [comment]
Cool @ileshmistry!

I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by ileshmistry** [comment]
Okay, that's now done @petrsvihlik 👍

**Comment by ileshmistry** [comment]
Hi @Simply007  you okay?

We’ve done some Kentico Cloud custom elements work for YouTube, but someone has already done some work on it, which is great! 
But how does it work, if we have something slightly different to what has been submitted?

**Comment by Simply007** [comment]
Hey @ileshmistry,

All good here, what about you?

If your implementation fits the issue's description, feel free to submit a pull request and reference it by using [Github closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to this issue.

If you have something different then described above, submit a pull request and we will review it as well and reference it to this issue, just for information purposes and let me know so that I can unassign this issue and let the people from the developer community know that it is available. 

The referenced pull request (#21) is the Youtube preview element, it is not a selector as described in this issue - it is just a reference to the related pull request.

Note: Please include the Readme file with element description in the pull request.
