### ISSUE TITLE
How to handle API keys

### ISSUE THREAD

**Issue by Bassetts** [Kentico/custom-element-samples#32]
The [documentation](https://developer.kenticocloud.com/docs/integrating-content-editing-features#section-json-parameters-in-the-ui) states 

> Warning: Never store your API keys or any other sensitive data in the JSON parameters field, it's not secure!

With this in mind how should API keys be stored? My [current solution](https://github.com/Bassetts/kc-youtube-picker/blob/master/components/Search.tsx#L2) is to have a `config.js` in the root of the project which contains a JSON object with the configuration values. 

The issue with this is the config file has to be added and then the custom element built with the devkit. This means I can't build the custom element to create a PR for the contest as the user needs to build it with the devkit to use their own API key.

**Comment by makma** [comment]
Related to #29 https://github.com/Kentico/custom-element-samples/pull/29#issuecomment-477141836

**Comment by makma** [comment]
Hi @Bassetts , I'm working on a solution how to handle sensitive data such as tokens and API keys while working with custom elements. I'll let you know as soon as possible. 

Since the sensitive data cannot be stored on the client, there will be probably AWS Lambda and/or Azure function sample serverless solution provided. This will also allow us to bypass CORS as well.

**Comment by kenticomartinh** [comment]
Hi @Bassetts, it depends on how "public" the API key is. If it is something that you would put into a public single page application (e.g. Google Maps API key or similar), typically if the key provides read-only permissions to something public anyway, you can very well put it into the config.

The point is primarily to prevent the editors (with limited permissions) from accessing the functionality (typically some management API) that they otherwise wouldn't be able to use.

Even if your management API key would be compiled in the element source code, such editors could retrieve it from the Browser tab simply by observing the requests made. So in case the API key is really private (exposes more than you are comfortable with), you need to make the call from somewhere where the user cannot access the request data, which would be typically some proxy function as @makma mentioned.

But it all depends on how private and potentially harmful your API key is.

**Comment by Bassetts** [comment]
@kenticomartinh Great, that makes sense. In my case it is for a Youtube API key so should be fine in the config 👌 I will leave this open for the case of API keys that should really be private.

**Comment by makma** [comment]
Hi @Bassetts, the solution for CORS bypass and storing sensitive data is implemented in https://github.com/Kentico/custom-element-samples/pull/33 (GET request only for a now). Let me know if it works for you.

**Comment by makma** [comment]
For future reference, [this comment ](https://github.com/Kentico/custom-element-samples/pull/49#issuecomment-483966902)describes when it is a good idea to store sensitive data in properties JSON.

**Comment by makma** [comment]
We've come up with some practice and decision rules when it's a good idea to store data into properties JSON. Please look at [this comment](https://github.com/Kentico/custom-element-samples/pull/49#issuecomment-483966902). @jancerman , could you add this to docu, please? Does it make sense for you?
